version: '3'
services:
  postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: mysupersecretpassword
      POSTGRES_USER: test
      POSTGRES_DB: db
    expose:
    - 5432
  app:
    image: node:14.4.0
    command: yarn start
    working_dir: /home/node
    volumes:
      - ./:/home/node
    links:
      - postgres
