version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: mysupersecretpassword
      POSTGRES_USER: test
      POSTGRES_DB: db
    expose:
    - 5432
  app:
    image: node
    command: yarn start
    working_dir: /home/node
    volumes:
      - ./:/home/node
